### ISSUE TITLE
header

### ISSUE THREAD

**Issue by uz6r** [uz6r/uz6r-dev#2]
#### tasks
- [ ] add icons for each subpages, use `heroicons` on LHS
- [ ] create a drawer for menus in small viewport (responsive)
- [ ] add darkmode toggle `kiv`
